KTL-156; use react on old site
JetBrains/kotlin-web-site pull request #1919
Opened 2020-10-12 09:00 UTC by zoobestik

2021-06-02 15:34 UTC, nikpachoo requested changes

2021-06-02 15:34 UTC, nikpachoo commented on package.json
> +    "@jetbrains/kotlin-web-site-ui": "2.0.5",
Please, up to 2.0.8

2021-06-02 15:34 UTC, nikpachoo commented on templates/base.html
> +    {% ktl_component "header" productGitHubUrl=data.releases.latest.url hasSearch=True %}
"productGitHubUrl" renamed to "productWebUrl"

2021-06-03 11:11 UTC, krutilov commented on package.json
> +    "@rescui/ui-contexts": "^0.0.2",
Consider using fixed version

2021-06-03 11:34 UTC, nikpachoo approved these changes

2021-06-04 07:49 UTC, krutilov approved these changes

2021-06-04 11:13 UTC, merged