Update basic-kotlin-native-app-codeblocks-code.md
JetBrains/kotlin-web-site pull request #1932
Opened 2020-10-28 22:29 UTC by Mazorius

* Update kotlin multiplatform to 1.3.72
* change mavenCentral() to jcenter()
* Update Gradle to 6.7

2020-11-20 06:42 UTC, p7nov requested changes
Hi! 
Thanks for the update!
I suggest making these samples even better by using variables for version numbers. They will update automatically and we won't run into this again.
Please see my comments and apply them to other occurrences of the same lines.

2020-11-20 06:42 UTC, p7nov commented on pages-includes/docs/tutorials/native/basic-kotlin-native-app-codeblocks-code.md
> +    id 'org.jetbrains.kotlin.multiplatform' version '1.3.72'
Let's use the placeholder for the latest stable version `{{ site.data.releases.latest.version }`:
```suggestion
    id 'org.jetbrains.kotlin.multiplatform' version '{{ site.data.releases.latest.version }'
```

2020-11-20 06:42 UTC, p7nov commented on pages-includes/docs/tutorials/native/basic-kotlin-native-app-codeblocks-code.md
> +  gradleVersion = "6.7"
There is a placeholder for Gradle version as well -  `{{ site.data.releases.tutorials.native.gradle_version }}`
However, it's now outdated. Please change the version here and update the placeholder in [/data/releases.yml](https://github.com/JetBrains/kotlin-web-site/blob/bd50bea578ed517765d18876d52accc93bd8d237/data/releases.yml#L25)

2020-11-30 09:42 UTC, Mazorius commented
Hi @p7nov 

I add the requested changes. I also change Gradle to the `BIN` distribution as `ALL` seems a bit to much.

Hopefully this suits your request ;-)

2020-12-01 05:09 UTC, p7nov approved these changes

2020-12-01 05:10 UTC, merged

2020-12-01 05:10 UTC, p7nov commented
Thank you for this update!