Add note about inlining of const vals
JetBrains/kotlin-web-site pull request #2489
Opened 2021-08-28 21:38 UTC by Starlight220

The current docs state what the limitations are and the ability to use constants in annotations, but nothing is said about what actually happens to them in regular code usages (which I think are much common). Having an outright statement in the docs would settle confusion that can arise from outdated/unclear YouTrack Issues and posts in Kotlin Discussions that slightly contradict.

2021-09-28 18:00 UTC, Starlight220 commented
Hello @koshachy, any chance for an update as to when this PR can be reviewed?

2021-09-29 08:04 UTC, koshachy commented
> Hello @koshachy, any chance for an update as to when this PR can be reviewed?

Hey @Starlight220 
Usually we handle external PRs in a month, but now we're a bit busy with the upcoming 1.6.0 release.
We'll review this PR in a week, I guess. Thanks for your patience!

2021-09-29 08:06 UTC, Starlight220 commented
No problem.
Excited for Kotlin 1.6!

2022-01-12 19:02 UTC, elizarov requested changes

2022-01-12 19:02 UTC, elizarov commented on docs/topics/properties.md
> +The compiler will inline usages of the constant, but will not remove the field (this can be useful when using [reflection](reflection.md)). For example, this Kotlin code compiles to the following Jav
I suggest clarifying what "inlines usages of the constant" means -> "inline usage of the constant during compilation, replacing the reference to the constant with its actual value".

2022-01-13 07:16 UTC, elizarov approved these changes

2022-01-14 09:17 UTC, koshachy commented
Thanks to everyone who participated in these changes :)

2022-01-14 09:17 UTC, merged