feat: new JS tutorial from the hands-on
JetBrains/kotlin-web-site pull request #2668
Opened 2021-11-22 14:07 UTC by danil-pavlov

2021-12-01 13:22 UTC, koshachy requested changes
Reviewed 525 lines in js-react.md
Will return later.

2022-02-28 16:32 UTC, AlexanderPrendota commented
Bad samples
Snippets:
File: docs/topics/js/js-react.md

```kotlin
import react.dom.*
import kotlinx.browser.document
import kotlinx.css.*
import kotlinx.serialization.Serializable
import styled.*

//sampleStart
fun main() {
   render(document.getElementById("root")) {
      h1 {
         +"Hello, React+Kotlin/JS!"
      }
   }
}
//sampleEnd
```

(0:7, 0:12) **ERROR** Unresolved reference: react
(1:15, 1:22) **ERROR** Unresolved reference: browser
(2:15, 2:18) **ERROR** Unresolved reference: css
(3:15, 3:28) **ERROR** Unresolved reference: serialization
(4:7, 4:13) **ERROR** Unresolved reference: styled
(8:3, 8:9) **ERROR** Unresolved reference: render
(8:10, 8:18) **ERROR** Unresolved reference: document
(9:6, 9:8) **ERROR** Unresolved reference: h1
(10:9, 10:10) **ERROR** Unresolved reference: +
    
------

2022-07-13 15:15 UTC, SebastianAigner requested changes
Some improvements here and there still possible, overall looking good!

2022-07-13 15:15 UTC, SebastianAigner commented on docs/topics/js/js-react.md
> +for the component. Use props `url` of the `String` type and a Boolean `controls`:
The "Use props"sentence has awk structure

2022-07-13 15:15 UTC, SebastianAigner commented on docs/topics/js/js-react.md
> +2. To use `react-share` from Kotlin, you'll need to write some basic external declarations. [Examples on GitHub](https://github.com/nygardk/react-share/blob/master/demo/Demo.tsx#L61)
"some more"?

2022-07-13 15:15 UTC, SebastianAigner commented on docs/topics/js/js-react.md
> +If buttons don't show up or work, you may need to disable your ad/social blocker for it to work.
repeats 'work' twice

2022-07-13 15:15 UTC, SebastianAigner commented on docs/topics/js/js-react.md
> +Check the `build.gradle(.kts)` file. The relevant snippet should already exist:
still no parens needed

2022-07-13 15:15 UTC, SebastianAigner commented on docs/topics/js/js-react.md
> +* _Suspending function_ makes a `fetch()` of a video from the API given an `id`. This response may take a while, so you `await()`
awkward, esp. "makes a fetch"

2022-07-19 21:42 UTC, SebastianAigner commented on docs/topics/js/js-react.md
> +* Learn how to use ready-made NPM components, use external libraries, and publish the final application.
npm isn't capitalized :)

2022-07-19 21:43 UTC, SebastianAigner commented on docs/topics/js/js-react.md
> +### Convert HTML to a typesafe HTML
"to Kotlin's typesafe HTML DSL", otherwise it doesn't work grammatically :)

2022-07-19 21:45 UTC, SebastianAigner commented on docs/topics/js/js-react.md
> +for the component. In this case, use props `url` and `controls`:
"use _the_ `url` and `controls` props"

2022-07-28 18:00 UTC, merged