update: release notes and tutorials
JetBrains/kotlin-web-site pull request #2903
Opened 2022-04-14 12:57 UTC by danil-pavlov

2022-04-15 08:40 UTC, yalishevant approved these changes

2022-04-18 13:56 UTC, koshachy requested changes
Double-check the **releases.md** file.
It has also information and links to the newest IDEA and plugin.

2022-04-18 13:56 UTC, koshachy commented on docs/topics/jvm/jvm-get-started.md
> +6. Select the **IntelliJ** build system. It's a native builder that doesn't require downloading additional artifacts.
Why IntelliJ?
Usually we don't promote it

2022-04-18 13:56 UTC, koshachy commented on docs/topics/jvm/jvm-get-started.md
> +6. Select the **IntelliJ** build system. It's a native builder that doesn't require downloading additional artifacts.
I don't think it's useful when we explain how to start a project with IntelliJ build system and then everywhere talk only about the Gradle/Maven.
What do you think?

2022-04-18 13:56 UTC, koshachy commented on docs/topics/jvm/jvm-get-started.md
> +8. Enable the **Add sample code** option to create a file with a sample `Hello World!` application.
Why **Hello World!** in the backticks?

2022-04-19 11:08 UTC, koshachy approved these changes
Discussed.
Approved, still requires small fixes.

2022-04-19 12:48 UTC, merged