Kotlin in Datalore
JetBrains/kotlin-web-site pull request #3084
Opened 2022-07-29 15:31 UTC by AlexBartholomew7

Suggest adding kotlin_in_datalore.png to https://github.com/JetBrains/kotlin-web-site/tree/master/docs/images/data-science
and using the commented-out <img/>

2022-08-01 16:19 UTC, koshachy requested changes
Thanks for the contribution.
Could you please take a look at the comments?

Feel free to contact me if you have any questions.

2022-08-01 16:19 UTC, koshachy commented on docs/topics/data-science-overview.md
> +Use Kotlin with a free Datalore Community account. [Register here].
Could you provide a link here?

2022-08-01 16:19 UTC, koshachy commented on docs/topics/data-science-overview.md
> +With Datalore, you can start using Kotlin in the browser straight out of the box, no installation required. You can also collaborate on Kotlin notebooks in real time, get smart coding assistance when
```suggestion
With Datalore, you can use Kotlin in the browser straight out of the box, no installation required. You can also collaborate on Kotlin notebooks in real time, get smart coding assistance when writing code, and share results as interactive or static reports. Check out a [sample report](https://datalore.jetbrains.com/view/report/9YLrg20eesVX2cQu1FKLiZ).
```

2022-08-08 05:20 UTC, AlexBartholomew7 commented on docs/topics/data-science-overview.md
> +Use Kotlin with a free Datalore Community account. [Register here].
http://jetbrains.com/datalore

2022-08-08 05:21 UTC, AlexBartholomew7 commented on docs/topics/data-science-overview.md
> +![kotlin_in_datalore](https://user-images.githubusercontent.com/73881741/181792090-9c9e0d75-1c2c-4e53-8e56-349b8bfe9921.png)
I cannot. I don't have access. 'Uploads are disabled'

2022-08-08 08:33 UTC, koshachy commented on docs/topics/data-science-overview.md
> +![kotlin_in_datalore](https://user-images.githubusercontent.com/73881741/181792090-9c9e0d75-1c2c-4e53-8e56-349b8bfe9921.png)
Oh, I see. So let's merge this one and then I'll update the pic in the separate PR.

2022-08-08 08:34 UTC, koshachy approved these changes
I'll upload and update the pic in the separate PR.

2022-08-08 08:49 UTC, merged

2022-08-08 09:07 UTC, koshachy commented
https://github.com/JetBrains/kotlin-web-site/pull/3099