New native dsl
JetBrains/kotlin-web-site pull request #3205
Opened 2022-10-05 15:04 UTC by danil-pavlov

2022-10-14 10:50 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +which can be consumed by Kotlin/Native itself as a dependency but cannot be executed or used as a native library.
The new DSL is only for libraries not for executables.
```
itself as a dependency but cannot be used as a native library.
```

2022-10-14 10:50 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +and provides a set of methods for declaring and configuring them.
```
To declare final native libraries, use the new ...
```

2022-10-14 10:52 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +The simplest version doesn't require any additional parameters and creates one binary for each build type. Currently,
It requires either a target or targets indeed

2022-10-14 10:54 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +}
```
kotlin {
    kotlinArtifacts {
        it.native.Library {
            target = iosX64 // Define your target instead
            modes(DEBUG, RELEASE)
            // Binary configuration
        }
    }
}
```

2022-10-14 10:55 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +}
```
kotlinArtifacts {
    it.native.Library("mylib") {
        // Binary configuration
    }
}
```

2022-10-14 10:58 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +produces the files `mylib.exe`.
For example, for Windows the code produces the file `mylib.dll`.

2022-10-14 11:00 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +− the usage of several Kotlin/Native modules in Swift is limited.
The problem exists for any native target not only for iOS

2022-10-14 11:01 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +and connect it to Swift.
With Kotlin artifact DSL, you can export multiple Kotlin modules into a single artifact.

2022-10-14 11:07 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +}
```
kotlinArtifacts {
    it.native.Library("mylib") {
        target = linuxX64
        kotlinOptions {
            freeCompilerArgs += "-Xmen=pool"
        }
    }
    it.native.Library("myslib") {
        target = linuxX64
        it.static = false
        modes(DEBUG)
        addModule(project(":lib"))
        kotlinOptions {
            verbose = false
            freeCompilerArgs = []
        }
    }
}
```

2022-10-14 11:08 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +}
```
kotlinArtifacts {
    it.native.Framework("myframe") {
        modes(DEBUG, RELEASE)
        target = iosArm64
        it.static = false
        embedBitcode = EmbedBitcodeMode.MARKER
        kotlinOptions {
            verbose = false
        }
    }
}
```

2022-10-14 11:09 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +| `embedBitcode` | Declares the mode of bitcode embedding. Use `MARKER` to embed the bitcode marker (for debug builds) or `DISABLE` to turn off embedding.                |
embedBitcode is not needed anymore with Xcode 14

2022-10-14 11:09 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +| `embedBitcode` | Declares the mode of bitcode embedding. Use `MARKER` to embed the bitcode marker (for debug builds) or `DISABLE` to turn off embedding.                |
but the option will be here for users anyway

2022-10-14 11:10 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +}
```
kotlinArtifacts {
    it.native.FatFramework("myfatframe") {
        targets(iosX32, ios64)
        embedBitcode = EmbedBitcodeMode.DISABLE
        kotlinOptions {
            suppressWarnings = false
        }
    }
}
```

2022-10-14 11:10 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +        targets(iosX32, ios64)
iosX64

2022-10-14 11:11 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +}
```
it.native.XCFramework("sdk") {
    targets(iosX64, iosArm64, iosSimulatorArm64)
    setModules(
        project(":shared"),
        project(":lib")
    )
}
```

2022-10-14 11:12 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +{type="warning"}
delete

2022-10-14 11:15 UTC, terrakok commented
It might be better:
 - for `library` and `framework` user has to setup `target`
 - for `fatframework` and `xcframework` user has to setup `targets`

For all Apple artifacts user can setup `embedBitcode` mode.

All other options are the same for all types of artifacts.

2022-10-14 11:16 UTC, terrakok commented
code examples some time contain `kotlin {}` block some time not. I think this should be consistent

2022-10-25 09:17 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +The simplest version requires the `target` (or `targets`) and `modes` parameters for the selected build type. Currently,
Only target (or targets) is required.
Modes have default value equal `modes(DEBUG, RELEASE)`

2022-10-25 09:18 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +produces the files `mylib.dll`.
`the file`

2022-10-25 09:20 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +Kotlin modules into a single artifact.
If your project has multiple Kotlin modules, and you need to access them from your iOS app, you'll encounter an issue − the usage of several Kotlin/Native **artifacts** in Swift is limited.

2022-10-25 09:25 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +```
```kotlin
kotlinArtifacts {
    Native.Library("myslib") {
        target = linuxX64
        isStatic = false
        modes(DEBUG)
        addModule(project(":lib"))
        kotlinOptions {
            verbose = false
            freeCompilerArgs += "-Xmen=pool"
        }
    }
}
```

2022-10-25 09:26 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +```
```groovy
kotlinArtifacts {
    it.native.Library("myslib") {
        target = linuxX64
        it.static = false
        modes(DEBUG)
        addModule(project(":lib"))
        kotlinOptions {
            verbose = false
            freeCompilerArgs += "-Xmen=pool"
        }
    }
}
```

2022-10-25 09:29 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +> If for some reason the new DSL doesn't work for you, try [this workaround](multiplatform-build-native-binaries.md#export-dependencies-to-binaries)
instead `this workaround` I would use `old approach`

2022-10-25 09:31 UTC, terrakok commented
For all code blocks need to delete `kotlin {}` wrapper

2022-10-25 14:36 UTC, terrakok commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +of the current project, but also the classes of its dependencies into a single entity and export all these modules to it.
`but also the classes of its dependencies` -> `but also the classes of any other multiplatform module`

2022-11-24 22:09 UTC, koshachy requested changes
Some minor comments.

2022-11-24 22:09 UTC, koshachy commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +| `targets`      | All targets of the project.
Declares all targets of the project?

2022-11-24 22:09 UTC, koshachy commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +The registered Gradle task is `assembleMyfatframeFatFramework` that assembles all types of registered "myfatframe" FatFramework.
"myfatframe" fat framework?

2022-11-24 22:09 UTC, koshachy commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +The registered Gradle task is `assembleSdkXCFramework` that assembles all types of registered "sdk" FatFramework.
"sdk" XCFramework?

2022-11-24 22:09 UTC, koshachy commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +Kotlin artifact DSL can help you solve a common issue, when your project has multiple Kotlin modules, and you need to
"issue: when your project" — this works for me better, but it's up to you.

2022-11-24 22:09 UTC, koshachy commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +Kotlin artifact DSL can help you solve a common issue, when your project has multiple Kotlin modules, and you need to
Kotlin artifact DSL can help you to solve a common issue: when you need to access multiple Kotlin modules from your app. 
Does this work?

2022-11-24 22:09 UTC, koshachy commented on docs/topics/multiplatform/multiplatform-native-artifacts.md
> +| `sharedLib`    | Shared native library   | All native targets, except for `WebAssembly` |
Maybe some links on what is "shared" and what is "static"? 🤔

2022-11-29 16:56 UTC, koshachy approved these changes
Niiiiice!

2022-11-29 19:33 UTC, merged