Add experimental Enum.entries and update examples
JetBrains/kotlin-web-site pull request #3430
Opened 2023-02-16 13:19 UTC by sarahhaggarty

Explain the new `entries` property for Enum classes. This page needs restructuring but I plan to do this in a separate PR to save time on review.

2023-02-21 13:38 UTC, zarechenskiy requested changes
Looks good, only minor notes, thank you!

2023-02-21 13:38 UTC, zarechenskiy commented on docs/topics/enum-classes.md
> +    println("The first color is: " + RGB.valueOf("RED")) // prints "The first color is: RED"
Minor: `println("The first color is: ${RGB.valueOf("RED")}")`

2023-02-21 13:38 UTC, zarechenskiy commented on docs/topics/enum-classes.md
> +> The `entries` property is [Experimental](components-stability.md#stability-levels-explained). To use it you need
Hmm, there is a problem that this compatibility guide is a bit incorrect and confuses technologies such as Kotlin/JVM and certain language features which should have their own definitions of compatibility levels. We are thinking about how to redesign it to include correct information about language features. I'd propose leaving the text as is, but remove the link to this guide, there should be enough explanation in `ExperimentalStdlibApi` annotation

2023-02-22 08:32 UTC, sarahhaggarty commented on docs/topics/enum-classes.md
> +If you don't want your enum constants returned in an array, you can use the `entries` property instead. The
Thanks @zarechenskiy! Can you check if the updated text is OK now?

2023-02-22 09:42 UTC, zarechenskiy approved these changes
👍

2023-03-08 11:44 UTC, closed without merging