Add Java synthetic property references KT-56313 1.8.20
JetBrains/kotlin-web-site pull request #3498
Opened 2023-03-24 14:32 UTC by PetrakovichVictoria

[KT-56313](https://youtrack.jetbrains.com/issue/KT-56313) [Docs][Language] Preview of Java synthetic property references

2023-03-24 15:15 UTC, PetrakovichVictoria commented on docs/topics/jvm/java-interop.md
> +### How to enable Java synthetic property references {initial-collapse-state="collapsed"}
I plan to replace it with the link to a constant section about it when this PR is ready https://github.com/JetBrains/kotlin-web-site/pull/3465/files

2023-03-24 15:19 UTC, nikitabobko requested changes

2023-03-24 15:23 UTC, PetrakovichVictoria commented on docs/topics/jvm/java-interop.md
> +Starting from Kotlin 1.8.20, you can create references to Java _synthetic properties_. For example, for such Java code:
Agree, thanks!

2023-03-26 18:40 UTC, PetrakovichVictoria commented
Something went wrong with git locally) A new PR is here https://github.com/JetBrains/kotlin-web-site/pull/3504

2023-03-26 18:40 UTC, closed without merging