Add Java synthetic property references
JetBrains/kotlin-web-site pull request #3504
Opened 2023-03-26 18:26 UTC by PetrakovichVictoria

[KT-56313](https://youtrack.jetbrains.com/issue/KT-56313) [Docs][Language] Preview of Java synthetic property references

2023-03-27 08:35 UTC, nikitabobko commented
Previous PR: https://github.com/JetBrains/kotlin-web-site/pull/3498

2023-03-27 08:40 UTC, nikitabobko requested changes

2023-03-27 08:40 UTC, nikitabobko commented on docs/topics/jvm/java-interop.md
> +also called _synthetic_.
I think it makes sense to mention the whole "synthetic properties" phrase in the definition to make it more clear

2023-03-27 13:21 UTC, nikitabobko approved these changes

2023-03-28 12:20 UTC, sarahhaggarty reviewed
Looking good! Again, just some minor suggestions. 😃

2023-03-28 12:20 UTC, sarahhaggarty commented on docs/topics/jvm/java-interop.md
> +`calendar.firstDayOfWeek` above is a synthetic property.
```suggestion
`calendar.firstDayOfWeek` above is an example of a synthetic property.
```

2023-03-28 12:20 UTC, sarahhaggarty commented on docs/topics/jvm/java-interop.md
> +> Use it only for evaluation purposes. We'd appreciate your feedback on it in [YouTrack](https://kotl.in/issue).
```suggestion
> We recommend that you use it only for evaluation purposes.
```
Danil asked me to not request feedback via YouTrack on experimental features in Docs. Only in what's new. So I guess the same applies here :)

2023-03-28 12:20 UTC, sarahhaggarty commented on docs/topics/jvm/java-interop.md
> +To try this feature out, enable the `-language-version 1.9` compiler option. In a Gradle project, you can do so
```suggestion
To enable this feature, set the `-language-version 1.9` compiler option. In a Gradle project, you can do so 
```

2023-03-28 18:58 UTC, merged