feat: add rangeUntil operator
JetBrains/kotlin-web-site pull request #3588
Opened 2023-05-23 14:22 UTC by sarahhaggarty

This PR updates our Ranges page with the `..<` operator. It also adds this operator the list of keywords and operators.

2023-05-24 09:51 UTC, zarechenskiy requested changes

2023-05-25 14:49 UTC, sarahhaggarty commented on docs/topics/ranges.md
> +    if (i in 1.rangeTo(4)) { // equivalent to i >= 1 && i <= 4
Guilty as charged! Fixed.

2023-05-31 12:59 UTC, zarechenskiy commented on docs/topics/ranges.md
> +    if (i in 1.rangeTo(4)) { // equivalent to i >= 1 && i <= 4
I think it's pretty clear now, thank you :)

2023-06-05 13:41 UTC, danil-pavlov commented on docs/topics/keyword-reference.md
> + * `..`, `..<` creates [ranges](ranges.md).
```suggestion
 * `..`, `..<` create [ranges](ranges.md).
```

2023-06-05 13:43 UTC, danil-pavlov commented on docs/topics/ranges.md
> +To create a closed-ended range, call the `.rangeTo()` function with the `..` operator.
```suggestion
To create a closed-ended range, call the `rangeTo()` function with the `..` operator.
```

2023-06-05 13:44 UTC, danil-pavlov commented on docs/topics/ranges.md
> +To create a closed-ended range, call the `.rangeTo()` function with the `..` operator.
```suggestion
To create a closed-ended range, call the `rangeTo()` function with the `..` operator.
```

2023-06-05 13:45 UTC, danil-pavlov commented on docs/topics/ranges.md
> +Kotlin lets you easily create ranges of values using the [`.rangeTo()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/range-to.html)
```suggestion
Kotlin lets you easily create ranges of values using the [`rangeTo()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/range-to.html)
```

2023-06-05 13:45 UTC, danil-pavlov commented on docs/topics/ranges.md
> +and [`.rangeUntil()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/range-until.html) functions from the
```suggestion
and [`rangeUntil()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/range-until.html) functions from the 
```

2023-06-05 13:46 UTC, danil-pavlov reviewed
I think it's worth adding the new operator to the [Idioms](https://kotlinlang.org/docs/idioms.html#iterate-over-a-range) page

2023-06-26 14:54 UTC, danil-pavlov approved these changes

2023-06-26 15:20 UTC, merged