minor fix for typo, link
JetBrains/kotlin-web-site pull request #3615
Opened 2023-06-08 20:19 UTC by mustfaunlu

2023-07-13 08:18 UTC, sarahhaggarty requested changes
Thanks for your suggestion @mustfaunlu! We only format "reified" as code when referring to the modifier so I have reverted these changes. I think the addition of the link is a great idea though! If you can take a look at my suggested changes, we can proceed to merge.

2023-07-13 08:18 UTC, sarahhaggarty commented on docs/topics/inline-functions.md
> +Normal functions (not marked as inline) cannot have `reified` parameters.
```suggestion
Normal functions (not marked as inline) cannot have reified parameters.
```

2023-07-13 08:18 UTC, sarahhaggarty commented on docs/topics/inline-functions.md
> +`Nothing`) cannot be used as an argument for a `reified` type parameter.
```suggestion
`Nothing`) cannot be used as an argument for a reified type parameter.
```

2023-07-13 19:59 UTC, mustfaunlu commented
Thank you for the clarification, @sarahhaggarty!

2023-07-14 11:54 UTC, koshachy approved these changes

2023-07-17 07:10 UTC, sarahhaggarty approved these changes

2023-07-17 07:20 UTC, merged