Rephrase definition of single-expression function
JetBrains/kotlin-web-site pull request #3639
Opened 2023-06-26 12:50 UTC by vegarsti

The current definition says "When a function returns a single expression", which I don't think is correct: As long as the return type is not `Void`, a function always returns a single expression. And it sounds as if the function returns all the expressions inside it.

This is an opinionated nitpick, though, so feel free to close this!

2023-07-19 11:25 UTC, sarahhaggarty requested changes
I agree that using "returns" is confusing. What do you think about this version that I suggest instead?

2023-07-19 11:25 UTC, sarahhaggarty commented on docs/topics/functions.md
> +When a function contains a single `return` expression, the curly braces can be omitted and the body is specified after a `=` symbol:
```suggestion
When the function body consists of a single expression, the curly braces can be omitted and the body specified after an `=` symbol:
```

2023-07-19 15:42 UTC, sarahhaggarty approved these changes

2023-07-19 16:21 UTC, merged

2023-07-19 16:22 UTC, sarahhaggarty commented
Thanks for sharing your thoughts with us @vegarsti !

2023-08-10 04:19 UTC, Cesar556 commented on docs/topics/functions.md
> +When a function contains a single `return` expression, the curly braces can be omitted and the body is specified after a `=` symbol:
- []()@_********_