fix kotlin tour functions (lambda expressions) documentation
JetBrains/kotlin-web-site pull request #3802
Opened 2023-09-24 15:02 UTC by alexey-ivanov-official

fix copy-pasted naming in "kotlin tour > functions > lambda expressions > pass to another function > map()" example

the term "predicate" seems to be copy-pasted from a nearby example of filter() method. 
the suitable term for map() method param is "transformer" I guess

2023-10-02 16:40 UTC, sarahhaggarty requested changes
Thanks for pointing this our @alexey-ivanov-official! This is indeed incorrect. I would like to use slightly different text. Could you make the changes?

2023-10-02 16:40 UTC, sarahhaggarty commented on docs/topics/tour/kotlin-tour-functions.md
> +The `.map()` function accepts a lambda expression as a transformer:
```suggestion
The `.map()` function accepts a lambda expression as a transform function:
```

2023-10-02 17:12 UTC, alexey-ivanov-official commented on docs/topics/tour/kotlin-tour-functions.md
> +The `.map()` function accepts a lambda expression as a transformer:
Yes. That's better. Thank you!

2023-10-04 10:17 UTC, sarahhaggarty approved these changes

2023-10-04 10:17 UTC, merged

2023-10-04 10:17 UTC, sarahhaggarty commented
Thanks for your contribution @alexey-ivanov-official !