fix: Indentation in save function
JetBrains/kotlin-web-site pull request #3876
Opened 2023-11-02 06:54 UTC by LightQuanta

2023-11-03 14:17 UTC, AlejandraPedroza commented on docs/topics/jvm/jvm-spring-boot-add-db-support.md
>          db.update("insert into messages values ( ?, ? )",
```suggestion
        db.update(
            "insert into messages values ( ?, ? )",
```

2023-11-03 14:19 UTC, AlejandraPedroza commented on docs/topics/jvm/jvm-spring-boot-add-db-support.md
>             message.id, message.text)
```suggestion
           message.id, message.text
        )
```

2023-11-03 14:24 UTC, AlejandraPedroza commented on docs/topics/jvm/jvm-spring-boot-add-db-support.md
>          db.update("insert into messages values ( ?, ? )",
```suggestion
        db.update(
            "insert into messages values ( ?, ? )",
```

2023-11-03 14:28 UTC, AlejandraPedroza commented on docs/topics/jvm/jvm-spring-boot-add-db-support.md
>                    id, message.text)
```suggestion
                  id, message.text
            )
```

2023-11-03 15:24 UTC, AlejandraPedroza requested changes
Hello @LightQuanta !
Thank you so much for pointing this out. Great catches!  Triggered by your formatting suggestions, we went ahead, checked the format in the whole two code snippets, and made a couple of tweaks. We’d like to apply these changes along with your suggestions. Would you mind adding them to your commit? In that way, we can merge all the updates together. 

Thanks for your help (:

2023-11-06 10:25 UTC, AlejandraPedroza commented on docs/topics/jvm/jvm-spring-boot-add-db-support.md
>              db.update("insert into messages values ( ?, ? )",
```suggestion
            db.update(
                "insert into messages values ( ?, ? )", 
```

2023-11-06 10:38 UTC, AlejandraPedroza commented on docs/topics/jvm/jvm-spring-boot-add-db-support.md
> +                id, message.text)
```suggestion
                id, message.text
            )
```

2023-11-06 10:40 UTC, AlejandraPedroza requested changes
Hi again @LightQuanta 
Thanks for going beyond! I formatted the whole code snippet that contains the last change you made. Could you please add the format updates to your commit so that we merge all together? Thanks!

2023-11-06 11:02 UTC, LightQuanta commented
> Hi again @LightQuanta Thanks for going beyond! I formatted the whole code snippet that contains the last change you made. Could you please add the format updates to your commit so that we merge all together? Thanks!

Done

2023-11-06 11:52 UTC, AlejandraPedroza approved these changes

2023-11-06 11:54 UTC, merged