update: adding wizard to Wasm Get started tutorial
JetBrains/kotlin-web-site pull request #4007
Opened 2024-02-01 11:26 UTC by AlejandraPedroza

Added wizard to the first part of the Get started tutorial, changed screenshots, and minor text updates.

2024-02-05 14:01 UTC, JSMonk approved these changes

2024-02-06 13:00 UTC, zamulla requested changes
Nice job!

Several things to note, in the comments.

2024-02-06 13:00 UTC, zamulla commented on docs/topics/wasm/wasm-get-started.md
> +2. On the **New Project** tab, change the project name to "ComposeDemo" and the project ID to "kmp.project.demo".
If we're guiding the user toward a purely Wasm project, the names here could reflect that. But it's just a suggestion :)

2024-02-06 13:00 UTC, zamulla commented on docs/topics/wasm/wasm-get-started.md
> +1. IntelliJ IDEA, open the **Gradle** tool window by selecting **View** | **Tool Windows** | **Gradle**.
```suggestion
1. In IntelliJ IDEA, open the **Gradle** tool window by selecting **View** | **Tool Windows** | **Gradle**.
```

2024-02-06 13:00 UTC, zamulla commented on docs/topics/wasm/wasm-get-started.md
> +   Alternatively, you can also run the following command in the terminal from the `composeApp` directory:
"Alternatively" doesn't need an "also," I think. It's already an alternative :)

2024-02-07 08:53 UTC, AlejandraPedroza commented on docs/topics/wasm/wasm-get-started.md
> +   You see a "Click me!" button. Click it:
I'm changing it to  "You can see a "Click me!" button" to keep it in the present tense. What do you think?

2024-02-07 11:28 UTC, zamulla approved these changes
LGTM!

2024-02-07 13:36 UTC, merged