Update idioms.md with suggestion to use inline value classes
JetBrains/kotlin-web-site pull request #4049
Opened 2024-02-22 16:33 UTC by gw111zz

2024-02-26 09:57 UTC, sarahhaggarty commented
Hi @gw111zz 
Thanks for your suggestion! Could you move your idiom lower in the document so that it's underneath the "Create a singleton" idiom?

2024-02-26 16:45 UTC, gw111zz commented
> Hi @gw111zz Thanks for your suggestion! Could you move your idiom lower in the document so that it's underneath the "Create a singleton" idiom?

Thanks for your comment @sarahhaggarty . I've made the suggested change.

2024-03-05 10:17 UTC, sarahhaggarty requested changes
Thanks for your suggestion @gw111zz !
I've suggested some changes to bring the text in line with our style guide. Please can you apply them? Then we can go ahead with the merge! 🚀

2024-03-05 10:17 UTC, sarahhaggarty commented on docs/topics/idioms.md
> +## Use inline value classes to wrap single values for type-safety
```suggestion
## Use inline classes for type-safe values
```

2024-03-05 10:17 UTC, sarahhaggarty commented on docs/topics/idioms.md
> +underlying type at runtime. `@JvmInline` is only needed for JVM backends.
```suggestion
If you accidentally mix up `EmployeeId` and `CustomerId`, a compilation error is triggered.

> The `@JvmInline` annotation is only needed for JVM backends.
>
{type="note"}
```

2024-03-05 10:17 UTC, sarahhaggarty commented on docs/topics/idioms.md
> +(See [Inline classes](inline-classes.md) for more information)
```suggestion
For more information, see [Inline value classes](inline-classes.md).
```

2024-03-14 08:34 UTC, sarahhaggarty commented
Hi @gw111zz 
Are you able to implement these changes? If I don't hear from you within a week, I'll combine these changes into another PR.

2024-03-21 09:26 UTC, sarahhaggarty commented
Changes add in #4088!

2024-03-21 09:26 UTC, closed without merging