Kotlin data analysis overview draft
JetBrains/kotlin-web-site pull request #4101
Opened 2024-03-27 13:31 UTC by AlejandraPedroza

2024-03-29 09:25 UTC, zaleslaw commented on docs/topics/data-analysis/data-analysis-connect-to-db.md
> +```kotlin
Hi, we updated our workflow/docs a little bit here https://kotlin.github.io/dataframe/readsqldatabases.html#getting-started-with-notebooks

Very important for user to run cell with the Database dependency earlier, before `use dataframe`

Please update the docs

2024-03-29 09:26 UTC, zaleslaw commented on docs/topics/data-analysis/data-analysis-visualization.md
> +## Create the data frame
data frame -> DataFrame?

2024-03-29 09:26 UTC, zaleslaw commented on docs/topics/data-analysis/data-analysis-visualization.md
> +You can see that the data frame has three columns: Month, Temperature, and City.
data frame -> DataFrame?

2024-03-29 09:28 UTC, zaleslaw requested changes
Please update section with SQL database exploration

2024-04-09 14:25 UTC, daniCsorbaJB requested changes
Thank you very much for this update 🚀  looks good - I left some comments 💬

2024-04-10 07:13 UTC, AlejandraPedroza commented on docs/topics/data-science-overview.md
> +Exploring and analyzing data is something you may not do every day as a software developer, but it is something you definitely need to tackle often.
Love it! Thanks for the suggestion.

2024-04-10 07:30 UTC, AlejandraPedroza commented on docs/topics/data-science-overview.md
> +software development duties that require your analytics skills.
I applied it but left it as "duties" to avoid repeating "scenarios".

2024-04-10 07:47 UTC, AlejandraPedroza commented on docs/topics/data-science-overview.md
> +* **Efficiently analyze data stored in relational databases:** Kotlin DataFrame seamlessly integrates with databases and provides capabilities similar to SQL queries.
I'll leave it as it is for DataFrame and Kandy (without adding 'library') in these introductory paragraphs and then, in their respective section, explain they are libraries.

2024-04-10 07:55 UTC, AlejandraPedroza commented on docs/topics/data-science-overview.md
> +Make the most of interactive editors while leveraging the perks of coding with Kotlin. Kotlin integrates with these notebooks
There's a previous paragraph containing this information over the GIF. Adding it here again would be repetitive. Any other recommendation to solve the "Make the most of interactive editors" sentence? The purpose of this complete sentence is to mention that with Kotlin notebooks, they can benefit from both the features of a notebook and the features of Kotlin as programming language.

2024-04-10 10:51 UTC, AlejandraPedroza commented on docs/topics/data-science-overview.md
> +capabilities to enhance your analytics skills and support you in the following scenarios:
I tried it, but it seemed wordy and a bit harder to get to the point. I'm using your wording but leaving it in a single sentence for conciseness.

2024-04-10 12:15 UTC, AlejandraPedroza commented on docs/topics/data-science-overview.md
> +Make the most of interactive editors while leveraging the perks of coding with Kotlin. Kotlin integrates with these notebooks
How about replacing it for: "With Kotlin notebooks, you can benefit from the features of a powerful interactive editor and the perks of coding with Kotlin." ?

2024-04-10 14:35 UTC, daniCsorbaJB approved these changes
Just added two small comments - great job! 🚀

2024-04-10 14:35 UTC, daniCsorbaJB commented on docs/topics/data-science-overview.md
> +With our Kotlin notebooks, you can benefit from the features of a powerful interactive editor and the perks of coding with Kotlin. Kotlin integrates with these notebooks
As we discussed, let's further discuss if we want to keep the part about the interactive editor here.

2024-04-11 11:04 UTC, merged