fix(ktl-1335): removed kotlin variable from test-page to ensure prope…
JetBrains/kotlin-web-site pull request #4114
Opened 2024-04-03 20:24 UTC by berezinant

…r testing by screenshots

2024-04-04 10:09 UTC, nikpachoo requested changes

2024-04-04 10:09 UTC, nikpachoo commented on docs/topics/test-page.md
> -    kotlin("kapt") version "%kotlinVersion%"
Why do we need to remove the variable? If it is a Docs functionality, I would like to keep it and adapt the tests.

2024-04-04 12:19 UTC, zoobestik approved these changes

2024-04-05 13:23 UTC, nikpachoo approved these changes

2024-04-05 13:24 UTC, merged