Update Groovy syntax from using the set() function
JetBrains/kotlin-web-site pull request #4294
Opened 2024-06-17 11:19 UTC by sarahhaggarty

This PR updates any instances in our docs where Groovy syntax uses the `set()` function and replaces it with an assignment operator.

2024-06-17 21:09 UTC, ALikhachev requested changes
Looking at these samples, I see another kind of inconsistency. 

1. In some samples we add import statements to reference classes by short names. (like here https://github.com/JetBrains/kotlin-web-site/blob/56844680abde3eb74de066df6634f2ad19d82074/docs/topics/gradle/gradle-compilation-and-caches.md#L336)
2. In other samples we reference classes by FQN (like here https://github.com/JetBrains/kotlin-web-site/blob/2b6165469b2102b845225b569f1cee1384db6416/docs/topics/gradle/gradle-configure-project.md#L192)
3. The most problematic case is when we reference classes by short names without import statement. (like here https://github.com/JetBrains/kotlin-web-site/blob/56844680abde3eb74de066df6634f2ad19d82074/docs/topics/gradle/gradle-compilation-and-caches.md#L248)

I think it should be addressed separately anyway

2024-06-17 21:09 UTC, ALikhachev commented on docs/topics/gradle/gradle-compilation-and-caches.md
>  tasks.withType(CompileUsingKotlinDaemon::class).configureEach { task ->
```suggestion
tasks.withType(CompileUsingKotlinDaemon).configureEach { task ->
```
Oh, we had this sample incorrect. This is a correction to make it work.

2024-06-17 21:09 UTC, ALikhachev commented on docs/topics/gradle/gradle-configure-project.md
> +        languageVersion = JavaLanguageVersion.of(<MAJOR_JDK_VERSION>))
```suggestion
        languageVersion = JavaLanguageVersion.of(<MAJOR_JDK_VERSION>)
```

2024-06-26 12:32 UTC, sarahhaggarty commented
> Looking at these samples, I see another kind of inconsistency.
> 
> 1. In some samples we add import statements to reference classes by short names. (like here https://github.com/JetBrains/kotlin-web-site/blob/56844680abde3eb74de066df6634f2ad19d82074/docs/topics/gradle/gradle-compilation-and-caches.md#L336
>    )
> 2. In other samples we reference classes by FQN (like here https://github.com/JetBrains/kotlin-web-site/blob/2b6165469b2102b845225b569f1cee1384db6416/docs/topics/gradle/gradle-configure-project.md#L192
>    )
> 3. The most problematic case is when we reference classes by short names without import statement. (like here https://github.com/JetBrains/kotlin-web-site/blob/56844680abde3eb74de066df6634f2ad19d82074/docs/topics/gradle/gradle-compilation-and-caches.md#L248
>    ) When one just copy-pastes such samples, they do not work without additional actions
> 
> I think this inconsistency should be addressed separately anyway

Thanks for pointing this out! I'll fix it in another PR :)

2024-07-10 19:03 UTC, ALikhachev approved these changes

2024-07-11 07:55 UTC, merged