update: deprecating android target
JetBrains/kotlin-web-site pull request #4536
Opened 2024-11-08 13:07 UTC by danil-pavlov

This PR updates the deprecation cycle for the old `android` target and replaces the remaining occurrences in the docs to `androidTarget`

2024-11-12 15:19 UTC, Tapchicoma approved these changes

2024-11-22 03:53 UTC, ElviraMustafina requested changes

2024-11-22 03:53 UTC, ElviraMustafina commented on docs/topics/multiplatform/multiplatform-compatibility-guide.md
> +* 2.1.0: report an error in such cases, causing the build to fail
This aligns better with the style of deprecation cycle lists:

```suggestion
* 1.9.0: introduce a deprecation warning when the `android` name is used in Kotlin Multiplatform projects
* 2.1.0: raise this warning to an error
```

2024-11-22 16:25 UTC, ElviraMustafina approved these changes

2024-11-22 16:51 UTC, merged