Intermediate tour: Classes chapter
JetBrains/kotlin-web-site pull request #4564
Opened 2024-11-20 11:54 UTC by sarahhaggarty

This PR is to add the second chapter of the intermediate tour to the staging branch.

2024-11-25 13:44 UTC, danil-pavlov requested changes
Huge work, maybe the most useful content on the website
My only concern again is the size of these chapters

I think It could be three pages, for example
1. Classes and interfaces 2. Objects 3. Open and other special classes
the 3rd page could be even a part of the Advanced tour

2024-12-02 15:26 UTC, sarahhaggarty commented on docs/topics/tour/kotlin-tour-intermediate-classes-part-1.md
> +Here, `param` is the name of the instance of the `Circle` class that the implementations of member functions are delegated to.
I think your suggestion is more formal than the original so I decided to keep the original version :)

2024-12-02 15:30 UTC, sarahhaggarty commented on docs/topics/tour/kotlin-tour-intermediate-classes-part-1.md
> +// write your code here
I didn't. But I like your suggestion :)

2024-12-02 15:47 UTC, sarahhaggarty commented on docs/topics/tour/kotlin-tour-intermediate-classes-part-2.md
> +Objects in Kotlin are lazy. They are only created once they are accessed. Kotlin also ensures that all objects are created
I chose both :) Thanks!

2024-12-02 15:57 UTC, sarahhaggarty commented on docs/topics/tour/kotlin-tour-intermediate-classes-part-2.md
> +type of [abstract class](kotlin-tour-intermediate-classes-part-1.md#abstract-classes). Once you declare that a class is sealed, you can only create child classes
It should be singular in this case as it's referring to the concept of an abstract class rather than multiple abstract classes.

2024-12-11 13:52 UTC, danil-pavlov commented on docs/topics/tour/kotlin-tour-intermediate-classes-part-1.md
> +Here, `param` is the name of the instance of the `Circle` class that the implementations of member functions are delegated to.
It's just a dangling preposition, but it's never critical;)

2024-12-11 15:58 UTC, merged