Update events.yml
JetBrains/kotlin-web-site pull request #4620
Opened 2024-12-19 09:28 UTC by Divy276

2025-01-15 15:09 UTC, meilalina approved these changes

2025-01-21 14:02 UTC, nikpachoo requested changes

2025-01-21 14:02 UTC, nikpachoo commented on data/events.yml
> +  - lang: pt
Thanks for the contribution!
The check failed because the formatting is broken.
Here's the fix
```suggestion
- lang: en
  startDate: '2025-02-22'
  endDate: '2025-02-22'
  location: Gurugram , India
  speaker: 'To be announced'
  title: 'UDAAN 2025'
  subject: 'Empowering Innovation Through Technology'
  url: https://www.commudle.com/communities/gurugram-kotlin-user-group/events/udaan-2025
- lang: pt
```

2025-01-21 14:35 UTC, nikpachoo approved these changes

2025-01-21 14:35 UTC, merged